const productsData = [
  {
    "category": "notebook",
    "brand": "Lenovo",
    "name": "ThinkPad",
    "processor": "Intel i5",
    "memory": "8GB",
    "storage": "256GB",
    "display": "15.6 inch",
    "price": "58000",
    "imagePath": "images/lenovo-thinkpad.jpg",
    "fixed": "true"
  },
  {
    "category": "notebook",
    "brand": "Lenovo",
    "name": "IdeaPad",
    "processor": "Intel i5",
    "memory": "4GB",
    "storage": "128GB",
    "display": "15.6 inch",
    "price": "42000",
    "imagePath": "images/lenovo-ideapad.jpg",
    "fixed": "true"
  },
  {
    "category": "notebook",
    "brand": "HP",
    "name": "Pavilion",
    "processor": "AMD Ryzen 3",
    "memory": "8GB",
    "storage": "128GB",
    "display": "15.6 inch",
    "price": "45000",
    "imagePath": "images/hp-pavilion.jpg",
    "fixed": "true"
  },
  {
    "category": "notebook",
    "brand": "HP",
    "name": "ProBook",
    "processor": "Intel i7",
    "memory": "4GB",
    "storage": "512GB",
    "display": "14 inch",
    "price": "93000",
    "imagePath": "images/hp-probook.jpg",
    "fixed": "true"
  },
  {
    "category": "notebook",
    "brand": "HP",
    "name": "Spectre",
    "processor": "Intel i7",
    "memory": "16GB",
    "storage": "1TB",
    "display": "15.6 inch",
    "price": "200000",
    "imagePath": "images/hp-spectre.jpg",
    "fixed": "true"
  },
  {
    "category": "notebook",
    "brand": "Acer",
    "name": "Swift",
    "processor": "Intel AMD Ryzen 5",
    "memory": "8GB",
    "storage": "512GB",
    "display": "15.6 inch",
    "price": "78000",
    "imagePath": "images/acer-swift.jpg",
    "fixed": "true"
  },
  {
    "category": "notebook",
    "brand": "Acer",
    "name": "Aspire",
    "processor": "Intel i3",
    "memory": "4GB",
    "storage": "128GB",
    "display": "15.6 inch",
    "price": "39000",
    "imagePath": "images/acer-aspire.jpg",
    "fixed": "true"
  },
  {
    "category": "notebook",
    "brand": "Acer",
    "name": "Aspire",
    "processor": "AMD Ryzen 3",
    "memory": "4GB",
    "storage": "128GB",
    "display": "15.6 inch",
    "price": "37000",
    "imagePath": "images/acer-aspire.jpg",
    "fixed": "true"
  },
  {
    "category": "notebook",
    "brand": "Asus",
    "name": "ZenBook",
    "processor": "Intel i5",
    "memory": "8GB",
    "storage": "256GB",
    "display": "15.6 inch",
    "price": "53000",
    "imagePath": "images/asus-zenbook.jpg",
    "fixed": "true"
  },
  {
    "category": "notebook",
    "brand": "Lenovo",
    "name": "Yoga",
    "processor": "Intel i5",
    "memory": "8GB",
    "storage": "256GB",
    "display": "14 inch",
    "price": "82000",
    "imagePath": "images/lenovo-yoga.jpg",
    "fixed": "true"
  },
  {
    "category": "notebook",
    "brand": "Asus",
    "name": "TUF",
    "processor": "AMD Ryzen 7",
    "memory": "8GB",
    "storage": "512GB",
    "display": "15.6 inch",
    "price": "141000",
    "imagePath": "images/asus-tuf.jpg",
    "fixed": "true"
  },
  {
    "category": "notebook",
    "brand": "Asus",
    "name": "ROG",
    "processor": "Intel i9",
    "memory": "16GB",
    "storage": "1TB",
    "display": "15.6 inch",
    "price": "263000",
    "imagePath": "images/asus-rog.jpg",
    "fixed": "true"
  },
  {
    "category": "notebook",
    "brand": "Dell",
    "name": "Vostro",
    "processor": "Intel i5",
    "memory": "8GB",
    "storage": "256GB",
    "display": "15.6 inch",
    "price": "63000",
    "imagePath": "images/dell-vostro.jpg",
    "fixed": "true"
  },
  {
    "category": "notebook",
    "brand": "Dell",
    "name": "Alienware",
    "processor": "Intel i7",
    "memory": "16GB",
    "storage": "512GB",
    "display": "15.6 inch",
    "price": "185000",
    "imagePath": "images/dell-alienware.jpg",
    "fixed": "true"
  },
  {
    "category": "notebook",
    "brand": "HP",
    "name": "Omen",
    "processor": "AMD Ryzen 7",
    "memory": "16GB",
    "storage": "512GB",
    "display": "17.3 inch",
    "price": "174000",
    "imagePath": "images/hp-omen.jpg",
    "fixed": "true"
  },
]

module.exports = productsData